### ISSUE TITLE
小米加载x264.142显示无法加载

### ISSUE THREAD

**Issue by kingling27** [wysaid/android-gpuimage-plus#18]
couldn't find "libx264.142.so"
	at java.lang.Runtime.loadLibrary(Runtime.java:366)
	at java.lang.System.loadLibrary(System.java:988)
	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:15)
	at org.wysaid.nativePort.CGEFrameRenderer.<clinit>(CGEFrameRenderer.java:14)
	at org.wysaid.view.VideoPlayerGLSurfaceView$9$1.run(VideoPlayerGLSurfaceView.java:487)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1462)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1239)
大神，求帮助回复！

**Comment by wysaid** [comment]
工程配置问题， 你是使用的我自带的demo就出现这个问题么

**Comment by kingling27** [comment]
大师兄，自带的demo没有问题，我是直接饮用的你的项目作为我的项目的依赖工程，请问还需要什么工程配置!求帮助回复！（问题记型是红米，arm64位的）

**Comment by wysaid** [comment]
see this: http://stackoverflow.com/questions/30782848/how-to-use-32-bit-native-libaries-on-64-bit-android-device

**Comment by kingling27** [comment]
已解决，谢谢！

**Comment by forgekxf** [comment]
x86 上可以跑起来吗？

**Comment by kingling27** [comment]
在部分x86上会有问题，在部分高端64位机子（mate 7、8、Vivo）也提示找不到so包，但是在红米上可以，还是希望作者提供不同平台so包！谢谢，项目已发布，用户反馈闪崩！非常感谢！

**Comment by wysaid** [comment]
@kingling27  好的~ 尽快~

**Comment by wysaid** [comment]
@kingling27  这个问题是可以解决的， 因为据我所知， 很多公司都是这样用的， 不需要armv7之外的so

**Comment by forgekxf** [comment]
小米5上面是无法运行的，提示找不到so包！还是希望作者提供不同平台so包！谢谢

**Comment by wysaid** [comment]
@forgekxf 小米5上面是可以运行的， 请去任何地方找一个“伙星” 这个app的apk包， 解开看看libCGE.so 以及 ffmpeg 是否只存在于 armv7a目录

**Comment by forgekxf** [comment]
小米5是android 6.0系统，arm-v8 CPU，只有把targetSdkVersion 改为22才能运行（兼容模式），目前targetSdkVersion 为23，若改为22，会造成升级版本无法覆盖安装，所以还是希望作者提供arm  so文件，非常感谢！！！

**Comment by wysaid** [comment]
@forgekxf fixed, please update
