### ISSUE TITLE
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.bhtc.huajuan-1/lib/arm/libx264.142.so: has text relocations

### ISSUE THREAD

**Issue by itheimaAndroid** [wysaid/android-gpuimage-plus#23]
java.lang.UnsatisfiedLinkError: dlopen failed: /data/app/com.bhtc.huajuan-1/lib/arm/libx264.142.so: has text relocations
                                                                      at java.lang.Runtime.loadLibrary(Runtime.java:372)
                                                                      at java.lang.System.loadLibrary(System.java:1076)
                                                                      at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:15)
                                                                      at org.wysaid.nativePort.CGEFrameRenderer.<clinit>(CGEFrameRenderer.java:11)
                                                                      at org.wysaid.view.CameraGLSurfaceView.onSurfaceCreated(CameraGLSurfaceView.java:413)
                                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1549)
                                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1286)

**Comment by itheimaAndroid** [comment]
大师兄，targetSdkVersion 23，6.0系统会报这个错误，目前项目的 targetSdkVersion 不能改，我觉得一劳永逸还是想办法吧libx264的编译搞好~~~

**Comment by wysaid** [comment]
fixed, please update
