### ISSUE TITLE
Random FFmpeg error in filter logic

### ISSUE THREAD

**Issue by Ashutosh-Tiwari** [wysaid/android-gpuimage-plus#275]
The filter logic in ffmpeg seems to have some issues. May be the `ffmpeg` processes needs to be killed manually in some cases. The issue was coming along with #68.
But now as the NDK has been updated #68 seems to be resolved but not this.
Also for your information @wysaid, it occurs randomly just like #68.
This log is all I have got:

```
Error running FFmpeg
java.lang.IllegalThreadStateException: Process has not yet terminated: 16893
at java.lang.ProcessManager$ProcessImpl.exitValue(ProcessManager.java:275)
at com.github.hiteshsondhi88.libffmpeg.CommandResult.getOutputFromProcess(CommandResult.java:18)
at com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:44)
at
com.github.hiteshsondhi88.libffmpeg.FFmpegExecuteAsyncTask.doInBackground(FFmpegExecuteAsyncTask.java:10)
at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
```

Please help me on this asap.

**Comment by wysaid** [comment]
You're using `com.github.hiteshsondhi88.libffmpeg`
I'm not familiar with the java wrapper of ffmpeg, maybe you should ask the [author](https://github.com/hiteshsondhi88) ?

**Comment by Ashutosh-Tiwari** [comment]
Oh.. Apologies @wysaid  I didn't check the log properly. Will take care of it.. Thanks anyways.. Closing
