### ISSUE TITLE
点击按钮时报错，都是同一个问题，日志如下

### ISSUE THREAD

**Issue by chenjiayulove** [wysaid/android-gpuimage-plus#352]
说得有点多，麻烦大神帮忙看看什么问题！！！！！！

首先项目一开始不能安装，提示
Installation failed with message INSTALL_FAILED_NO_MATCHING_ABIS: Failed to extract native libraries, res=-113.
It is possible that this issue is resolved by uninstalling an existing version of the apk if it is present, and then re-installing.
按照网上解决方法在项目build下添加了这几句代码就可以正常安装了
splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi-v7a', 'x86_64'
            universalApk true
        }
    }

但项目不能运行，报错日志
07-30 17:02:24.945 994-994/org.wysaid.cgedemo E/AndroidRuntime: FATAL EXCEPTION: main
                                                                Process: org.wysaid.cgedemo, PID: 994
                                                                java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.wysaid.cgedemo-3PKjeZ_zzHCyT4yyyfUjrA==/base.apk"],nativeLibraryDirectories=[/data/app/org.wysaid.cgedemo-3PKjeZ_zzHCyT4yyyfUjrA==/lib/x86, /system/lib]]] couldn't find "libffmpeg.so"
                                                                    at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                    at java.lang.System.loadLibrary(System.java:1669)
                                                                    at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:22)
                                                                    at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
                                                                    at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
                                                                    at org.wysaid.cgeDemo.MainActivity.onCreate(MainActivity.java:240)
                                                                    at android.app.Activity.performCreate(Activity.java:7130)
                                                                    at android.app.Activity.performCreate(Activity.java:7121)
                                                                    at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1262)
                                                                    at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
                                                                    at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
                                                                    at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                    at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:110)
                                                                    at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
                                                                    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800)
                                                                    at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                    at android.os.Looper.loop(Looper.java:164)
                                                                    at android.app.ActivityThread.main(ActivityThread.java:6649)
                                                                    at java.lang.reflect.Method.invoke(Native Method)
                                                                    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
按照报错的代码  我把(NativeLibraryLoader.java:22)那个你注释掉的try catch重新使用就能运行到主界面

但点击主界面按钮时报如下错误
.cgedemo E/.wysaid.cgedem: No implementation found for long org.wysaid.nativePort.CGEImageHandler.nativeCreateHandler() (tried Java_org_wysaid_nativePort_CGEImageHandler_nativeCreateHandler and Java_org_wysaid_nativePort_CGEImageHandler_nativeCreateHandler__)
                                                                    
                                                                    --------- beginning of crash
07-30 16:53:33.880 26906-27021/org.wysaid.cgedemo E/AndroidRuntime: FATAL EXCEPTION: GLThread 549
                                                                    Process: org.wysaid.cgedemo, PID: 26906
                                                                    java.lang.UnsatisfiedLinkError: No implementation found for long org.wysaid.nativePort.CGEImageHandler.nativeCreateHandler() (tried Java_org_wysaid_nativePort_CGEImageHandler_nativeCreateHandler and Java_org_wysaid_nativePort_CGEImageHandler_nativeCreateHandler__)
                                                                        at org.wysaid.nativePort.CGEImageHandler.nativeCreateHandler(Native Method)
                                                                        at org.wysaid.nativePort.CGEImageHandler.<init>(CGEImageHandler.java:22)
                                                                        at org.wysaid.view.ImageGLSurfaceView.onSurfaceCreated(ImageGLSurfaceView.java:246)
                                                                        at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1539)
                                                                        at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1270)
再次打开APP到主界面就报下面错误
07-30 17:09:08.604 5167-5167/org.wysaid.cgedemo E/libCGE_java: Load library for 'cge' failed! Please check your project config.
                                                               java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/org.wysaid.cgedemo-IDrVH0E6M0xD1_1VSBb4jg==/base.apk"],nativeLibraryDirectories=[/data/app/org.wysaid.cgedemo-IDrVH0E6M0xD1_1VSBb4jg==/lib/x86, /system/lib]]] couldn't find "libffmpeg.so"
                                                                   at java.lang.Runtime.loadLibrary0(Runtime.java:1012)
                                                                   at java.lang.System.loadLibrary(System.java:1669)
                                                                   at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:22)
                                                                   at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
                                                                   at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
                                                                   at org.wysaid.cgeDemo.MainActivity.onCreate(MainActivity.java:240)
                                                                   at android.app.Activity.performCreate(Activity.java:7130)
                                                                   at android.app.Activity.performCreate(Activity.java:7121)
                                                                   at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1262)
                                                                   at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2905)
                                                                   at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3060)
                                                                   at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:78)
                                                                   at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:110)
                                                                   at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:70)
                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1800)
                                                                   at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                   at android.os.Looper.loop(Looper.java:164)
                                                                   at android.app.ActivityThread.main(ActivityThread.java:6649)
                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
只有点击第四个按钮正常

**Comment by chenjiayulove** [comment]
是需要重新编译.so文件吗   要怎么编译运行呢

**Comment by wysaid** [comment]
才看到... 我这边运行时好好的呀
项目文件比较旧, 没有适配最新的安卓系统策略, 这块你自己改改吧?
项目内置了一个apk文件, 你先试试看有没有你说的问题吧

**Comment by AanalShah** [comment]
> Is it necessary to recompile the .so file? How do I compile and run it?

no you can use [this ready .so file ](https://github.com/wysaid/android-gpuimage-plus-libs)  for all architure 

for architecture x86_64 , temporary solution  [is this](https://github.com/wysaid/android-gpuimage-plus/issues/373#issuecomment-440141995)
