### ISSUE TITLE
incompatibility problem

### ISSUE THREAD

**Issue by greadking** [wysaid/android-gpuimage-plus#386]
dlopen("/data/app/com.mp.morepick-1/lib/arm/libCGE.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_register_all" referenced by "libCGE.so"...
UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_register_all" referenced by "libCGE.so"..

**Comment by greadking** [comment]
@wysaid Please give me a hand

**Comment by wysaid** [comment]
Does it happen in the builtin demo?

**Comment by greadking** [comment]
I think it is compile error, dome of senior brother is ok

**Comment by greadking** [comment]
@wysaid I'm using dome's. So it's still going to be the same problem I'm trying to solve ‘https://blog.csdn.net/u013578413/article/details/47149553’ Still no problem solved

**Comment by greadking** [comment]
@wysaid I used dome in my brother's again and tried so, the above error would still appear 
Here's the full error

[2018-11-23 11:37:23.480] [25828] [25828] [3] [STATUSBAR_DEBUG] : vivo statusbar style 
[2018-11-23 11:37:23.480] [25828] [25828] [3] [STATUSBAR_DEBUG] : windowDrawsFlag set
[2018-11-23 11:37:23.480] [25828] [25828] [3] [STATUSBAR_DEBUG] : IconColor=1
[2018-11-23 11:37:23.480] [25828] [25828] [3] [STATUSBAR_DEBUG] : StatusBarColor final set ffe5e5e5
[2018-11-23 11:37:23.500] [25828] [25828] [3] [horizontalscroll] : vivo style=false
[2018-11-23 11:37:23.510] [25828] [25828] [6] [art] : dlopen("/data/app-1/lib/arm/libCGE.so", RTLD_LAZY) failed: dlopen failed: cannot locate symbol "av_register_all" referenced by "libCGE.so"...
[2018-11-23 11:37:23.510] [25828] [25828] [3] [AndroidRuntime] : Shutting down VM
[2018-11-23 11:37:23.630] [265] [26509] [3] [libc-netbsd] : _resolv_set_default_nameservers_for_net, 2063, return, not recovery mode
[2018-11-23 11:37:23.630] [265] [26509] [3] [libc-netbsd] : _resolv_set_default_nameservers_for_net, 2063, return, not recovery mode
[2018-11-23 11:37:23.630] [265] [26509] [3] [libc-netbsd] : netid=100, dns0:114.114.114.114
[2018-11-23 11:37:23.630] [265] [26509] [3] [libc-netbsd] : netid=100, dns1:8.8.8.8
[2018-11-23 11:37:23.640] [4314] [4314] [3] [StatusBar.MSimNetworkController] : refreshViews phoneId =0mMSimDataConnected =false
[2018-11-23 11:37:23.640] [4314] [4314] [3] [StatusBar.MSimNetworkController] : refreshViews mMSimDataActivity =0
[2018-11-23 11:37:23.640] [4314] [4314] [3] [VivoNetworkController] : SystemUI|mWifiEnabled && mWifiConnected = true
[2018-11-23 11:37:23.640] [4314] [4314] [3] [StatusBar.MSimNetworkController] : refreshViews: Data not connected!! Set no data type icon / Roaming for phoneId: 0
[2018-11-23 11:37:23.640] [4314] [4314] [3] [StatusBar.MSimNetworkController] : refreshViews connected={ } level=0 mMSimcombinedSignalIconId=0x7f020376/com.android.systemui:drawable/stat_sys_signal_null mMSimcombinedActivityIconId=0x0 mAirplaneMode=false mMSimDataActivity=0 mMSimPhoneSignalIconId=0x7f020376/com.android.systemui:drawable/stat_sys_signal_null mMSimDataDirectionIconId=0x0 mMSimDataSignalIconId=0x7f020376 mMSimDataTypeIconId=0x0/(null) mNoMSimIconId=0x0/(null) mMSimMobileActivityIconId=0x0/(null) mWifiIconId=0x0 mBluetoothTetherIconId=0x10806ab
[2018-11-23 11:37:23.770] [2169] [4119] [6] [WifiStateMachine] : calculateWifiScore() we set wifi's score to 1000, so will always set wifi as a default network.
[2018-11-23 11:37:23.840] [4613] [5747] [3] [DataUsageService] : 
[2018-11-23 11:37:23.870] [25828] [25828] [6] [AndroidRuntime] : FATAL EXCEPTION: main
Process: , PID: 25828
java.lang.UnsatisfiedLinkError: dlopen failed: cannot locate symbol "av_register_all" referenced by "libCGE.so"...
	at java.lang.Runtime.loadLibrary(Runtime.java:372)
	at java.lang.System.loadLibrary(System.java:989)
	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:19)
	at comick.ui.find.HandleMediaActivity.initView(HandleMediaActivity.java:264)
	at comck.ui.find.HandleMediaActivity.initEvent(HandleMediaActivity.java:182)
	at com.pick.base.BaseMvpAct.onCreate(BaseMvpAct.java:52)
	at android.app.Activity.performCreate(Activity.java:6024)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2317)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2426)
	at android.app.ActivityThread.access$900(ActivityThread.java:155)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1331)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5318)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:922)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:717)

**Comment by wysaid** [comment]
Please try this: https://github.com/wysaid/android-gpuimage-plus/tree/master/demoRelease
To see if the problem exist in the builtin demo.

**Comment by greadking** [comment]
大师兄 是中国人吧 我可以打中文问了 这个dome是可以正常运行的 在我的项目中使用了跟dome相同的 os库 但是在 5.x的部分手机中会出现上面的问题不能找到av_register_all这个方法 我想不到是什么地方犯了错误

**Comment by greadking** [comment]
> 请试试这个：[https](https://github.com/wysaid/android-gpuimage-plus/tree/master/demoRelease)：[//github.com/wysaid/android-gpuimage-plus/tree/master/demoRelease](https://github.com/wysaid/android-gpuimage-plus/tree/master/demoRelease)
> 查看内置演示中是否存在问题。

大师兄 是中国人吧 我可以打中文问吧 这个dome是可以正常运行的 在我的项目中使用了跟dome相同的 os库 但是在 5.x的部分手机中会出现上面的问题不能找到av_register_all这个方法 我想不到是什么地方犯了错误

**Comment by greadking** [comment]
> 你自己的工程里面应该是包含了多个架构的c++库, 你需要把这个工程里面所有架构的动态库文件都加上.

大师兄的意思是说 7个cpu的 so库都要 加载项目中吗？

**Comment by wysaid** [comment]
你也可以把除了 armv7 之外的全部删掉， 然后只用这一个架构， 就没事了.
你自己拆一下市面上的类似app看看，看他们一般有哪些架构， 然后决定上哪些

**Comment by greadking** [comment]
好的 感谢大师兄的 回答 等下我会试一下  解决了 在答复大师兄

**Comment by greadking** [comment]
@wysaid 大师兄 我发现问题了 是因为 我之前用到了其他的库 和 ffmpeg.so冲突 我 选择直接将 我们CEG中的名字重命名 然后修改System.loadLibrary("ffmpeg1");  造成了上面的问题 不过我想知道 如果我想要 自己编译 重新生成新的名字不是 “ffmpeg”的 so库  要修改哪里  修改名称问什么会造成低端手机找不到  av_register_all方法

**Comment by wysaid** [comment]
> @wysaid 大师兄 我发现问题了 是因为 我之前用到了其他的库 和 ffmpeg.so冲突 我 选择直接将 我们CEG中的名字重命名 然后修改System.loadLibrary("ffmpeg1"); 造成了上面的问题 不过我想知道 如果我想要 自己编译 重新生成新的名字不是 “ffmpeg”的 so库 要修改哪里 修改名称问什么会造成低端手机找不到 av_register_all方法

你可以改成任何名字， 但是你得重新编译代码， 这个repo提供了所有代码的， 你只需要链接你的ffmpeg然后重新编译就行了
