### ISSUE TITLE
录视频时so报错

### ISSUE THREAD

**Issue by chenjiayulove** [wysaid/android-gpuimage-plus#402]
我项目使用的SO架构是armeabi-v7a
引用你这边的是   plus:2.6.1-armv7a  
在录制视频的时候调用NativeLibraryLoader.load();报下错
cannot locate symbol "avcodec_alloc_frame" referenced by "/data/app/com.mp.morepick-1/lib/arm/libCGE.so"
有的手机不会出现  但其他手机出现频率蛮高
直接使用你这个库也没用   plus:2.6.1
请问是so文件我要怎么配置

**Comment by chenjiayulove** [comment]
对so库不太熟悉

**Comment by chenjiayulove** [comment]
先点下拍照后再去点录视频就没问题   但直接录视频就有问题  是不是FFmpeg和cge的问题啊

**Comment by wysaid** [comment]
@chenjiayulove 请问使用内置的demo 有这个问题吗

**Comment by chenjiayulove** [comment]
我还是好早之前down下来的  刚刚运行只有点击simple playerdemo能进去  其他按钮都崩溃

**Comment by wysaid** [comment]
@chenjiayulove https://github.com/wysaid/android-gpuimage-plus/tree/master/demoRelease
试一下这个吧， 一个月以前更新的

**Comment by chenjiayulove** [comment]
好的  我到时再看看更新的代码  有问题再来请教   3Q

**Comment by chongbo2013** [comment]
我重新编译 buildJni 后，打开app报错误了，之前可以
` java.lang.UnsatisfiedLinkError: No implementation found for void org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll() (tried Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll and Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll__)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll(Native Method)
        at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:12)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.<clinit>(CGEFFmpegNativeLibrary.java:10)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll(Native Method)
        at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:12)
        at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
        at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
        at org.wysaid.cgeDemo.MainActivity.onCreate(MainActivity.java:242)
        at android.app.Activity.performCreate(Activity.java:6758)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1122)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2806)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2918)
        at android.app.ActivityThread.-wrap12(ActivityThread.java)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1628)
        at android.os.Handler.dispatchMessage(Handler.java:110)
        at android.os.Looper.loop(Looper.java:203)
        at android.app.ActivityThread.main(ActivityThread.java:6406)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:974)`
