### ISSUE TITLE
setFilterIntensityForIndex

### ISSUE THREAD

**Issue by Jiang00** [wysaid/android-gpuimage-plus#404]
你好，@adjust whitebalance 1 1@vignette 0.5 0.7 使用setFilterIntensityForIndex没有效果

**Comment by Jiang00** [comment]
还有那个libcge.so这个库怎么重新编译，搞了一晚上还是搞不通，cmake分支运行失败：
Build command failed.
Error while executing process C:\Users\86183\AppData\Local\Android\Sdk\cmake\3.10.2.4988404\bin\cmake.exe with arguments {--build E:\ziliao\android-gpuimage-plus-cmake\library\.externalNativeBuild\cmake\debug\armeabi-v7a --target CGE}
[0/1] Re-running CMake...
-- Configuring done
-- Generating done
-- Build files have been written to: E:/ziliao/android-gpuimage-plus-cmake/library/.externalNativeBuild/cmake/debug/armeabi-v7a
[1/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeDynamicWaveFilter.cpp.o
[2/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeDynamicFilters.cpp.o
[3/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeExposureAdjust.cpp.o
[4/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeBrightnessAdjust.cpp.o
[5/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeColorBalanceAdjust.cpp.o
[6/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeFilterBasic.cpp.o
[7/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeCurveAdjust.cpp.o
[8/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeEdgeFilter.cpp.o
[9/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeEmbossFilter.cpp.o
[10/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeColorLevelAdjust.cpp.o
[11/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeAdvancedEffects.cpp.o
[12/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeBeautifyFilter.cpp.o
[13/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeBilateralBlurFilter.cpp.o
[14/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeAdvancedEffectsCommon.cpp.o
[15/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeContrastAdjust.cpp.o
[16/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeBlendFilter.cpp.o
[17/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeCrosshatchFilter.cpp.o
[18/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeDataParsingEngine.cpp.o
[19/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMaxValueFilter.cpp.o
[20/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMidValueFilter.cpp.o
[21/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMinValueFilter.cpp.o
[22/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMonochromeAdjust.cpp.o
[23/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeLookupFilter.cpp.o
[24/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeHueAdjust.cpp.o
[25/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeColorMappingFilter.cpp.o
[26/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeLerpblurFilter.cpp.o
[27/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMotionFlowFilter.cpp.o
[28/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgePolarPixellateFilter.cpp.o
[29/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMosaicBlurFilter.cpp.o
[30/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeSaturationAdjust.cpp.o
[31/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgePolkaDotFilter.cpp.o
[32/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMultipleEffectsCommon.cpp.o
[33/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeRandomBlurFilter.cpp.o
[34/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeCommonDefine.cpp.o
[35/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeHalftoneFilter.cpp.o
[36/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeMultipleEffects.cpp.o
[37/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeLiquidationFilter.cpp.o
[38/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeGlobal.cpp.o
[39/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeHazeFilter.cpp.o
[40/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeGLFunctions.cpp.o
[41/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeImageFilter.cpp.o
[42/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeShaderFunctions.cpp.o
[43/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeTiltshiftAdjust.cpp.o
[44/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeShadowHighlightAdjust.cpp.o
[45/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeImageHandler.cpp.o
[46/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/common/cgeTextureUtils.cpp.o
[47/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeSharpenBlurAdjust.cpp.o
[48/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeVignetteAdjust.cpp.o
[49/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFFmpegNativeLibrary.cpp.o
[50/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/extends/cgeThread.cpp.o
[51/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeSketchFilter.cpp.o
[52/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeSelectiveColorAdjust.cpp.o
[53/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/filters/cgeWhiteBalanceAdjust.cpp.o
[54/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeSharedGLContext.cpp.o
[55/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRendererWrapper.cpp.o
[56/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeNativeLibrary.cpp.o
[57/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeImageHandlerAndroid.cpp.o
[58/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeImageHandlerWrapper.cpp.o
[59/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeVideoDecoder.cpp.o
[60/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeUtilFunctions.cpp.o
[61/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRecorderWrapper.cpp.o
[62/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRenderer.cpp.o
[63/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRecorder.cpp.o
FAILED: src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRecorder.cpp.o 
D:\android-ndk-r14b\toolchains\llvm\prebuilt\windows-x86_64\bin\clang++.exe --target=armv7-none-linux-androideabi --gcc-toolchain=D:/android-ndk-r14b/toolchains/arm-linux-androideabi-4.9/prebuilt/windows-x86_64 --sysroot=D:/android-ndk-r14b/platforms/android-14/arch-arm  -DCGE_EXPORTS -I../../../../src/main/jni/cge/../include -I../../../../src/main/jni/cge/../interface -I../../../../src/main/jni/cge/../include/filters -I../../../../src/main/jni/cge/../ffmpeg -I../../../../src/main/jni/cge/../cge -isystem D:/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/include -isystem D:/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/libs/armeabi-v7a/include -isystem D:/android-ndk-r14b/sources/cxx-stl/gnu-libstdc++/4.9/include/backward -frtti -std=gnu++11  -D_CGE_USE_FFMPEG_ -DDEBUG -DANDROID_NDK -DCGE_TEXTURE_PREMULTIPLIED=1 -D__STDC_CONSTANT_MACROS -D_CGE_DISABLE_GLOBALCONTEXT_ -O3 -ffast-math -D_CGE_ONLY_FILTERS_ -O0 -fno-limit-debug-info  -fPIC -MD -MT src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRecorder.cpp.o -MF src\main\jni\cge\CMakeFiles\CGE.dir\__\interface\cgeFrameRecorder.cpp.o.d -o src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeFrameRecorder.cpp.o -c ../../../../src/main/jni/interface/cgeFrameRecorder.cpp
../../../../src/main/jni/interface/cgeFrameRecorder.cpp:94:12: error: use of undeclared identifier 'bufferSize'
                                assert(bufferSize != 0); // bufferSize must be set!
                                       ^
1 error generated.
[64/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeVideoPlayer.cpp.o
[65/66] Building CXX object src/main/jni/cge/CMakeFiles/CGE.dir/__/interface/cgeVideoEncoder.cpp.o
ninja: build stopped: subcommand failed.

**Comment by wysaid** [comment]
Read [this](https://github.com/wysaid/android-gpuimage-plus#abstract)

**Comment by Jiang00** [comment]
$ sh buildJNI
buildJNI:行14: 未预期的符号 `$'do\r'' 附近有语法错误
'uildJNI:行14: `do
然后把这一块删了报语法错误
$ ./buildJNI
./buildJNI:行64: 语法错误: 未预期的文件结尾

**Comment by wysaid** [comment]
@Jiang00 use cygwin or mingw.

**Comment by Jiang00** [comment]
是用的cygwin，找到原因了，用notpad++修改了一下buildJNI文件，windows模式改为Unix模式就好了

**Comment by Jiang00** [comment]
你好，编译是成功了，但是生成的libCGE.so只有466kb,而且运行崩溃，我看别人之前的提问buildjn有
export CGE_USE_VIDEO_MODULE=1。
   java.lang.UnsatisfiedLinkError: No implementation found for void org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll() (tried Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll and Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll__)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll(Native Method)
        at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:12)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.<clinit>(CGEFFmpegNativeLibrary.java:10)
        at org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll(Native Method)
        at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:12)
        at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
        at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
        at org.wysaid.cgeDemo.MainActivity.onCreate(MainActivity.java:242)
        at android.app.Activity.performCreate(Activity.java:7050)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2809)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2931)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1620)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:176)
        at android.app.ActivityThread.main(ActivityThread.java:6701)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:246)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:783)
麻烦大师兄解惑

**Comment by wysaid** [comment]
@Jiang00 Are you using the latest code of master?
And please paste all output of your build.

**Comment by Jiang00** [comment]
是最新的代码http://llpsgsb.oss-cn-hongkong.aliyuncs.com/lib/armeabi-v7a.zip

**Comment by wysaid** [comment]
> 是最新的代码http://llpsgsb.oss-cn-hongkong.aliyuncs.com/lib/armeabi-v7a.zip

@Jiang00 把jni同级目录下的 `libs`, `obj` 目录删了重新编译

**Comment by Jiang00** [comment]
哇，可以啦，感谢，

**Comment by Jiang00** [comment]
我在cgeVignetteAdjust.cpp这个文件里修改暗角颜色不起作用，还是黑色
bool CGEVignetteExtFilter::init()
	{
		if(initShadersFromString(g_vshDefaultWithoutTexCoord, s_fshVignetteLinear))
		{
			setVignetteCenter(0.5f, 0.5f);
			setVignetteColor(1.0f, 0.0f, 0.0f);
			return true;
		}
		return false;
	}
