### ISSUE TITLE
Library for X84 64bit architecture, Google warning

### ISSUE THREAD

**Issue by nguyenvp08** [wysaid/android-gpuimage-plus#409]
Hi I'm using the library for image filter, and I see that there is only x86 (32bit) architecture is supported but x86_64 bit is not. And Google will ban the app that not support both architecture as the link below : https://android-developers.googleblog.com/2019/01/get-your-apps-ready-for-64-bit.html.

Can you help provide the x86 64 bit architecture!

**Comment by wysaid** [comment]
OK, I will do it recently.
Also you can do it yourself, just put the x86_64 libraries(opencv, ffmpeg) between the other archs, and rebuild.
If you're not using the recording module, you can also try the `min` branch. All archs are supported.

**Comment by nguyenvp08** [comment]
Hi @wysaid, can you help to provide these library cause i'm not confident at pick up the library, maybe something wrong happen (wrong version ?), I think it's easy for you to handle this thing of work, I really appreciate your helpful library. 

But btw somehow the library still can be run perfectly on a x86_64 bit CPU Android Emulator, but I see that the library has no x86_64 library folder (only x86 folder), can you help me to explain it ?

**Comment by zenghao1556** [comment]
请问你最后编译出x86_64的.so吗？  我也需要一份

**Comment by deepakrokz** [comment]
Hi @wysaid ,

Please, please, please add this .so file compatible with x86_64

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/issues/451

**Comment by deepakrokz** [comment]
Hi @wysaid , 
Hope you are doing well!
Can you please look into this:

> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.test-zJ3d6mH3S1Q-czUhAsOdpw==/lib/x86/libffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
        at java.lang.System.loadLibrary(System.java:1669)
        at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:18)
        at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
        at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
        at com.canlah.MuzibeesApp.onCreate(MuzibeesApp.java:711)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
        at android.app.ActivityThread.access$1100(ActivityThread.java:199)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6669)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

I will be very thankful to you if you can help me with this.

**Comment by wysaid** [comment]
> Hi @wysaid ,
> Hope you are doing well!
> Can you please look into this:
> 
> > java.lang.UnsatisfiedLinkError: dlopen failed: "/data/app/com.test-zJ3d6mH3S1Q-czUhAsOdpw==/lib/x86/libffmpeg.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
> > at java.lang.Runtime.loadLibrary0(Runtime.java:1016)
> > at java.lang.System.loadLibrary(System.java:1669)
> > at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:18)
> > at org.wysaid.nativePort.CGENativeLibrary.(CGENativeLibrary.java:18)
> > at org.wysaid.nativePort.CGENativeLibrary.setLoadImageCallback(CGENativeLibrary.java:76)
> > at com.canlah.MuzibeesApp.onCreate(MuzibeesApp.java:711)
> > at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
> > at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5871)
> > at android.app.ActivityThread.access$1100(ActivityThread.java:199)
> > at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
> > at android.os.Handler.dispatchMessage(Handler.java:106)
> > at android.os.Looper.loop(Looper.java:193)
> > at android.app.ActivityThread.main(ActivityThread.java:6669)
> > at java.lang.reflect.Method.invoke(Native Method)
> > at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> > at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
> 
> I will be very thankful to you if you can help me with this.

It's finding the `x86` version  of ffmpeg,  please check if your package contains that one?

**Comment by deepakrokz** [comment]
yes, it has all the required variants of abiFilters 'armeabi-v7a', 'arm64-v8a', 'x86', 'x86_64'

from [here](https://github.com/wysaid/android-gpuimage-plus/tree/dev/master/library/src/main/libs) for gpu image and for running external FFMPEG commands for audio operations using [this]( https://github.com/yadavkohi/FFmpegAndroid).

Please review once and let me know which one is causing issue and any suggestion for resolving this.
Thanks for your prompt response.

**Comment by wysaid** [comment]
The all archs are provided.
