### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found

### ISSUE THREAD

**Issue by gurkanlus-library** [wysaid/android-gpuimage-plus#504]
when I run the app on device sdk 32, it gives me this error:
UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found

but there is no error on sdk 30

**Comment by wysaid** [comment]
Which version are you using?
Please link the source code if it's reported by the prebuilt AAR.

**Comment by ahmadbajwa8282** [comment]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1091)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1664)
       at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:10)
       at org.wysaid.nativePort.CGEImageHandler.<clinit>(CGEImageHandler.java)
       at org.wysaid.view.ImageGLSurfaceView.onSurfaceCreated(ImageGLSurfaceView.java:17)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by wysaid** [comment]
Hi, did this happen with the source version?  `jcenter` is deprecated, and the library is out of date.

**Comment by Asad-noor** [comment]
This issue is still happening. can you please explain how to fix this issue? @wysaid

**Comment by wysaid** [comment]
> This issue is still happening. can you please explain how to fix this issue? @wysaid

The `jcenter` is deprecated, and I can't upgrade the library.  Please link the source project by now.
And I will try to create the ` MavenCentral` library later.
