### ISSUE TITLE
UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found

### ISSUE THREAD

**Issue by ahmadbajwa8282** [wysaid/android-gpuimage-plus#507]
Fatal Exception: java.lang.UnsatisfiedLinkError: dlopen failed: library "libffmpeg.so" not found
       at java.lang.Runtime.loadLibrary0(Runtime.java:1091)
       at java.lang.Runtime.loadLibrary0(Runtime.java:1011)
       at java.lang.System.loadLibrary(System.java:1664)
       at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:10)
       at org.wysaid.nativePort.CGEImageHandler.<clinit>(CGEImageHandler.java)
       at org.wysaid.view.ImageGLSurfaceView.onSurfaceCreated(ImageGLSurfaceView.java:17)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1541)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)

**Comment by wysaid** [comment]
Did this happen with the repo builtin demo?

**Comment by ahmadbajwa8282** [comment]
No In my production app.
