### ISSUE TITLE
CGEImageHandler.nativeGetResultBitmap

### ISSUE THREAD

**Issue by epegasus** [wysaid/android-gpuimage-plus#524]
I'm facing this crash, reported via firebase-crashlytics.

### Device Details

android 12 11 10
samsung, oppo, xiaomi, transsion

### Trace

java.lang.IllegalArgumentException - width and height must be > 0

Fatal Exception: java.lang.IllegalArgumentException: width and height must be > 0
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1237)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1204)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1154)
       at android.graphics.Bitmap.createBitmap(Bitmap.java:1115)
       at org.wysaid.nativePort.CGEImageHandler.nativeGetResultBitmap(CGEImageHandler.java)
       at org.wysaid.nativePort.CGEImageHandler.getResultBitmap(CGEImageHandler.java:41)
       at org.wysaid.view.ImageGLSurfaceView$7.run(ImageGLSurfaceView.java:271)
       at com.google.android.gms.common.api.internal.zao.run(com.google.android.gms:play-services-base@@18.0.0:15)
       at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1510)
       at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1280)

**Comment by wysaid** [comment]
Get. You're calling getResultBitmap with a  0x0 resolution.
Add a check here: https://github.com/wysaid/android-gpuimage-plus/pull/526

**Comment by wysaid** [comment]
Please try the latest version of the source.
