### ISSUE TITLE
NativeLibraryLoader.load (java.lang.UnsatisfiedLinkError)

### ISSUE THREAD

**Issue by epegasus** [wysaid/android-gpuimage-plus#525]
This issue is closed because:

1. **Feature request**: WebP support
2. **Android platform feature**: Use BitmapFactory

Thank you!

**Comment by wysaid** [comment]
I'm not facing this problem. 
Have you checked your lib?  
Provide more details about your devices?

**Comment by ferhatozcelik** [comment]
```
Process: com.app, PID: 4895
                                                                                                    java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-T-M59gvJEjRDcL1kchX0Q==/com.app-534UeA9JG8li7Q7f0EZUaA==/base.apk!/lib/arm64-v8a/libCGE.so" (new hash type from the future?)
```
                                                                                                    
```
at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
                                                                                                    	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
                                                                                                    	at java.lang.System.loadLibrary(System.java:1765)
                                                                                                    	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:15)
                                                                                                    	at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
                                                                                                    	at com.app.activities.ImageEditActivity.onCreate(ImageEditActivity.java:197
```)                                                                                                    
                                                                                                    
                                                                                                    
**Device**
Pixel 8 API 35 (Android Studio Emulator)

**Comment by wysaid** [comment]
> ```
> Process: com.app, PID: 4895
>                                                                                                     java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-T-M59gvJEjRDcL1kchX0Q==/com.app-534UeA9JG8li7Q7f0EZUaA==/base.apk!/lib/arm64-v8a/libCGE.so" (new hash type from the future?)
> ```
> 
> ```
> at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
>                                                                                                     	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
>                                                                                                     	at java.lang.System.loadLibrary(System.java:1765)
>                                                                                                     	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:15)
>                                                                                                     	at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
>                                                                                                     	at com.app.activities.ImageEditActivity.onCreate(ImageEditActivity.java:197
> ```)      
> 
> **Device**
> Pixel 8 API 35 (Android Studio Emulator)                                                                                                      
>                                                                                             
>                                                                                                                                                                                                
>                                                                                                     
>                                                                                                     
> ```

You're using emulator,  please check if you are using the right arch of libs.

**Comment by ferhatozcelik** [comment]
> > ```
> > Process: com.app, PID: 4895
> >                                                                                                     java.lang.UnsatisfiedLinkError: dlopen failed: empty/missing DT_HASH/DT_GNU_HASH in "/data/app/~~-T-M59gvJEjRDcL1kchX0Q==/com.app-534UeA9JG8li7Q7f0EZUaA==/base.apk!/lib/arm64-v8a/libCGE.so" (new hash type from the future?)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ```
> > at java.lang.Runtime.loadLibrary0(Runtime.java:1081)
> >                                                                                                     	at java.lang.Runtime.loadLibrary0(Runtime.java:1003)
> >                                                                                                     	at java.lang.System.loadLibrary(System.java:1765)
> >                                                                                                     	at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:15)
> >                                                                                                     	at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
> >                                                                                                     	at com.app.activities.ImageEditActivity.onCreate(ImageEditActivity.java:197
> > ```)      
> > 
> > **Device**
> > Pixel 8 API 35 (Android Studio Emulator)                                                                                                      
> >                                                                                             
> >                                                                                                                                                                                                
> >                                                                                                     
> >                                                                                                     
> > ```
> 
> You're using emulator, please check if you are using the right arch of libs.



       ```
 maven { url 'https://maven.wysaid.org/' }

    //All arch: armeabi-v7a, arm64-v8a, x86, x86_64 without video module (no ffmpeg)
    implementation 'org.wysaid:gpuimage-plus:3.0.0-min'
```
    Yes, I checked API 33 and 34, there is no problem, but 35 also causes crash. Could you please look at this issue in detail, can you check the necessary conditions etc. for API 35, thank you.

**Comment by wysaid** [comment]
<img width="1633" alt="image" src="https://github.com/user-attachments/assets/baaf8bb6-0ea1-4765-9ead-870b9f774e6d">
hello, @ferhatozcelik   ,  I tried with my demo, the problem did not come.  Can you please give me more details or if you can produce this problem on my demo?

**Comment by qinRight** [comment]
大师兄，我的也有这个问题，模拟器要选这个16kb page  size，demo就会崩溃
![WX20241118-104011@2x](https://github.com/user-attachments/assets/e80959fd-f38f-47a0-b34a-04709da5b375)

**Comment by qinRight** [comment]
> <img alt="image" width="1633" src="https://private-user-images.githubusercontent.com/1430725/359045967-baaf8bb6-0ea1-4765-9ead-870b9f774e6d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE4OTU3NjEsIm5iZiI6MTczMTg5NTQ2MSwicGF0aCI6Ii8xNDMwNzI1LzM1OTA0NTk2Ny1iYWFmOGJiNi0wZWExLTQ3NjUtOWVhZC04NzBiOWY3NzRlNmQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDExMThUMDIwNDIxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODU0NTk4YTI3MzYxNzViMDU5ZDNlZmIyMGI4YWI3ZDA4Yjc2MDRjNDgxMTc4YTFhOGY3Yzc0MDkzYTY2YjdhYyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.PyynJysCF4u-jJQppW02HdrsJ33Fkv4ezL4TLjciTCM"> hello, @ferhatozcelik , I tried with my demo, the problem did not come. Can you please give me more details or if you can produce this problem on my demo?
> 你好，我尝试了我的演示，问题没有出现。您能否给我更多详细信息，或者您是否可以在我的演示中产生这个问题？

大师兄，我的也有这个问题，模拟器要选这个16kb page  size，demo就会崩溃
![WX20241118-104011@2x](https://github.com/user-attachments/assets/e80959fd-f38f-47a0-b34a-04709da5b375)

**Comment by qinRight** [comment]
升级一下就好了：https://developer.android.com/guide/practices/page-sizes?hl=zh-cn#cmake
