### ISSUE TITLE
NDK 编译工程启动报错

### ISSUE THREAD

**Issue by jiriyao** [wysaid/android-gpuimage-plus#68]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: org.wysaid.cgedemo, PID: 25268
                  java.lang.UnsatisfiedLinkError: No implementation found for void org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll() (tried Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll and Java_org_wysaid_nativePort_CGEFFmpegNativeLibrary_avRegisterAll__)
                      at org.wysaid.nativePort.CGEFFmpegNativeLibrary.avRegisterAll(Native Method)
                      at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:23)
                      at org.wysaid.nativePort.CGENativeLibrary.<clinit>(CGENativeLibrary.java:18)
                      at org.wysaid.cgeDemo.MainActivity.onCreate(MainActivity.java:239)
                      at android.app.Activity.performCreate(Activity.java:6286)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1113)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2603)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2720)
                      at android.app.ActivityThread.-wrap12(ActivityThread.java)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1567)
                      at android.os.Handler.dispatchMessage(Handler.java:111)
                      at android.os.Looper.loop(Looper.java:207)
                      at android.app.ActivityThread.main(ActivityThread.java:5917)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:888)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:749)

试了不同的NDK 版本和 不同的机器（mac）都出现这个错误，大师兄救救吧：）

**Comment by NSDM** [comment]
我也遇到这个问题，代码一点都没改，自己编译的库一运行就找不到 avRegisterAll，求救啊，大师兄

**Comment by jiriyao** [comment]
把cgeFFmpegNativeLibrary 类里的=》 #ifdef _CGE_USE_FFMPEG_ 判断去掉就可以运行成功了：）

**Comment by wysaid** [comment]
都是完全不看说明么……
export CGE_USE_VIDEO_MODULE=1
用自带的编译脚本或者在编译前加上这个临时环境变量就行了。
或者应该改一改脚本的……

**Comment by jiriyao** [comment]
export CGE_USE_VIDEO_MODULE=1 
这个语句肯定是执行了的

**Comment by wysaid** [comment]
你能直接使用哪个 buildJNI 脚本不， 这个应该是没问题的

**Comment by Ashutosh-Tiwari** [comment]
@wysaid I am also facing this issue and just not getting where to resolve and what to resolve. Please help

**Comment by Ashutosh-Tiwari** [comment]
@jiriyao I did not understand what you did for the solution to this problem and also the translation to English was a bit improper. Can you please explain me properly how to resolve it?

**Comment by jiriyao** [comment]
@Ashutosh-Tiwari 
in cgeFFmpegNativeLibrary class, deleted the line   #ifdef CGE_USE_FFMPEG , It worked

**Comment by Ashutosh-Tiwari** [comment]
@wysaid @jiriyao i believe this line #ifdef CGE_USE_FFMPEG already removed and still i am facing the same issue with samsung and MI devices.
is there any hardware related issue ? 
Please help , thanks.

**Comment by Ashutosh-Tiwari** [comment]
@wysaid  Sir, any updates? I am still stuck with it.

**Comment by wysaid** [comment]
@Ashutosh-Tiwari 
It's fixed!  https://github.com/wysaid/android-gpuimage-plus/issues/269#issuecomment-355890097

**Comment by Ashutosh-Tiwari** [comment]
No implementation found for long org.wysaid.nativePort.CGEFrameRenderer.nativeCreateRenderer() (tried Java_org_wysaid_nativePort_CGEFrameRenderer_nativeCreateRenderer and Java_org_wysaid_nativePort_CGEFrameRenderer_nativeCreateRenderer__)
ava.lang.UnsatisfiedLinkError: No implementation found for long org.wysaid.nativePort.CGEFrameRenderer.nativeCreateRenderer() (tried Java_org_wysaid_nativePort_CGEFrameRenderer_nativeCreateRenderer and Java_org_wysaid_nativePort_CGEFrameRenderer_nativeCreateRenderer__)
                                                                                      at org.wysaid.nativePort.CGEFrameRenderer.nativeCreateRenderer(Native Method)
                                                                                      at org.wysaid.nativePort.CGEFrameRenderer.<init>(CGEFrameRenderer.java:17)
                                                                                      at org.wysaid.view.VideoPlayerGLSurfaceView$9$1.run(VideoPlayerGLSurfaceView.java:488)
                                                                                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
                                                                                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)

@wysaid M still receiving this error randomly. Using the latest version of your library. What should I do??

**Comment by wysaid** [comment]
Is this reported on the built-in demo or your own app?

**Comment by Ashutosh-Tiwari** [comment]
No.. I have used your library in my own app, following your demo logic in TestCaseActivity. @wysaid

**Comment by wysaid** [comment]
@Ashutosh-Tiwari 
Maybe you're using multi archs.
To solve this, you can leave only `armeabi-v7a` for your native libraries, and delete all others.
Or you should add all versions of `libCGE.so` (like arm64, x86...)
