### ISSUE TITLE
UnsatisfiedLinkError on x86_64 devices

### ISSUE THREAD

**Issue by enginebai** [wysaid/android-gpuimage-plus#95]
I run your demo code on Android Studio Emulator, but it crashed.

```java
E/AndroidRuntime: FATAL EXCEPTION: GLThread 313
                  Process: PID: 12056
                  java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/*/base.apk"],nativeLibraryDirectories=[/data/app/*-1/lib/x86_64, /data/app/*-1/base.apk!/lib/x86_64, /vendor/lib64, /system/lib64]]] couldn't find "libffmpeg.so"
                      at java.lang.Runtime.loadLibrary(Runtime.java:367)
                      at java.lang.System.loadLibrary(System.java:1076)
                      at org.wysaid.nativePort.NativeLibraryLoader.load(NativeLibraryLoader.java:18)
                      at org.wysaid.nativePort.CGEFrameRenderer.<clinit>(CGEFrameRenderer.java:11)
                      at org.wysaid.view.VideoPlayerGLSurfaceView$9$1.run(VideoPlayerGLSurfaceView.java:487)
                      at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1463)
                      at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1240)
```

I've built via `buildJNI`, but there is no any `x86_64` *.so files. How can I fix that?

**Comment by wysaid** [comment]
make sure there's only armv7a in lib folder(delete all others)
run, and see the result

**Comment by enginebai** [comment]
OK, thanks.

Another problem, I've applied filter when starting to play video, and once my app goes background (going through `onPause()` / `onResume()`), the filter was gone. How can I keep filter when app returns from background?

**Comment by enginebai** [comment]
OK, thanks.

**Comment by wysaid** [comment]
https://github.com/wysaid/android-gpuimage-plus/issues/451
